In [3]:
import matplotlib.pyplot as plt
import pandas as pd
from sktime.utils.plotting import plot_series

In [24]:
PATH_DATA_XLSX = '../data/xlsx'
PATH_DATA_CSV = '../data/csv'

In [26]:
# getting files

from os import listdir
from os.path import isfile, join

xlsxfiles = [f for f in listdir(PATH_DATA_XLSX) if isfile(join(PATH_DATA_XLSX, f))]
csvfiles = [f for f in listdir(PATH_DATA_CSV) if isfile(join(PATH_DATA_CSV, f))]

In [45]:
print(xlsxfiles)

['Borrow4DEC.xlsx', 'Lend4DEC.xlsx', 'BorrowOCT31.xlsx', 'LendOCT31.xlsx']

In [46]:
print(csvfiles)

['Pairs-Price_31OCT.csv', 'PairPrices4DEC.csv']

In [27]:
print("xlsxfiles", len(xlsxfiles))
print("csvfiles", len(csvfiles))

xlsxfiles 4
csvfiles 2

In [25]:
PATH = f"{PATH_DATA_XLSX}/{xlsxfiles[0]}"

data = pd.read_excel(PATH, index_col=0)
data.head()

,Time,ASUSD,AUSDT,ADAI,AYFI,AKNC,AETH,AREN,ALINK,ATUSD,...,ALEND.1,AREP.1,AENJ.1,AUSDC.1,ASNX.1,ABAT.1,ABUSD.1,AZRX.1,AMANA.1,AWBTC.1
Platform,,,,,,,,,,,,,,,,,,,,,
Aave,2020-10-10T19:48:30.438035456Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19832611692982600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063063,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:49:53.165059911Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19832611692982600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063063,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:51:14.445774448Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19832611692982600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063064,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:52:36.592969518Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19835748095272600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063064,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:53:58.036531289Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19835748095272600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063064,0.007688,0.038797,0.004982,0.002178,0.002934

In [53]:
print(len(data))
print(data3.columns)

57876
Index(['Time', 'ASUSD', 'AUSDT', 'ADAI', 'AYFI', 'AKNC', 'AETH', 'AREN',
       'ALINK', 'ATUSD', 'AMKR', 'ALEND', 'AREP', 'AENJ', 'AUSDC', 'ASNX',
       'ABAT', 'ABUSD', 'AZRX', 'AMANA', 'AWBTC', 'ASUSD.1', 'AUSDT.1',
       'ADAI.1', 'AYFI.1', 'AKNC.1', 'AETH.1', 'AREN.1', 'ALINK.1', 'ATUSD.1',
       'AMKR.1', 'ALEND.1', 'AREP.1', 'AENJ.1', 'AUSDC.1', 'ASNX.1', 'ABAT.1',
       'ABUSD.1', 'AZRX.1', 'AMANA.1', 'AWBTC.1'],
      dtype='object')

In [43]:
data.iloc[len(data) - 1]['Time']

'2020-12-04T17:26:38.130554028Z'

In [29]:
PATH = f"{PATH_DATA_XLSX}/{xlsxfiles[1]}"

data2 = pd.read_excel(PATH, index_col=0)
data2.head()

,Time,ADAI,AUSDC,ATUSD,ASUSD,AWBTC,AKNC,ABAT,ABUSD,AETH,...,AUSDT.1,AMANA.1,AZRX.1,ASNX.1,AYFI.1,ALINK.1,AREN.1,AREP.1,AENJ.1,ALEND.1
Platform,,,,,,,,,,,,,,,,,,,,,
Aave,2020-10-10T19:48:30.438035456Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3232423846207670,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013900,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:49:53.165059911Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3232423846207670,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013900,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:51:14.445774448Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3232423846207670,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013901,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:52:36.592969518Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3233439206158070,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013901,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:53:58.036531289Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3233439206158070,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013901,0.005158,0.000525,0.001148,0.000012,0.000244,9.383208e-07

In [51]:
print(len(data2))
print(data2.columns)

57876
Index(['Time', 'ADAI', 'AUSDC', 'ATUSD', 'ASUSD', 'AWBTC', 'AKNC', 'ABAT',
       'ABUSD', 'AETH', 'AMKR', 'AUSDT', 'AMANA', 'AZRX', 'ASNX', 'AYFI',
       'ALINK', 'AREN', 'AREP', 'AENJ', 'ALEND', 'ADAI.1', 'AUSDC.1',
       'ATUSD.1', 'ASUSD.1', 'AWBTC.1', 'AKNC.1', 'ABAT.1', 'ABUSD.1',
       'AETH.1', 'AMKR.1', 'AUSDT.1', 'AMANA.1', 'AZRX.1', 'ASNX.1', 'AYFI.1',
       'ALINK.1', 'AREN.1', 'AREP.1', 'AENJ.1', 'ALEND.1'],
      dtype='object')

In [44]:
data2.iloc[len(data2) - 1]['Time']

'2020-12-04T17:26:38.130554028Z'

In [30]:
PATH = f"{PATH_DATA_XLSX}/{xlsxfiles[2]}"

data3 = pd.read_excel(PATH, index_col=0)
data3.head()

,Time,ASUSD,AUSDT,ADAI,AYFI,AKNC,AETH,AREN,ALINK,ATUSD,...,ALEND.1,AREP.1,AENJ.1,AUSDC.1,ASNX.1,ABAT.1,ABUSD.1,AZRX.1,AMANA.1,AWBTC.1
Platform,,,,,,,,,,,,,,,,,,,,,
Aave,2020-10-10T19:48:30.438035456Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19832611692982600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063063,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:49:53.165059911Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19832611692982600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063063,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:51:14.445774448Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19832611692982600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063064,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:52:36.592969518Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19835748095272600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063064,0.007688,0.038797,0.004982,0.002178,0.002934
Aave,2020-10-10T19:53:58.036531289Z,45890356713640496,44141825491673200,60779224199156096,28654820705014700,19835748095272600,31640169521277000,13362042572053000,8886191178756400,17689277091621700,...,0.000259,0.000658,0.006167,0.034477,0.063064,0.007688,0.038797,0.004982,0.002178,0.002934

In [60]:
set(data3.columns)

{'ABAT',
 'ABAT.1',
 'ABUSD',
 'ABUSD.1',
 'ADAI',
 'ADAI.1',
 'AENJ',
 'AENJ.1',
 'AETH',
 'AETH.1',
 'AKNC',
 'AKNC.1',
 'ALEND',
 'ALEND.1',
 'ALINK',
 'ALINK.1',
 'AMANA',
 'AMANA.1',
 'AMKR',
 'AMKR.1',
 'AREN',
 'AREN.1',
 'AREP',
 'AREP.1',
 'ASNX',
 'ASNX.1',
 'ASUSD',
 'ASUSD.1',
 'ATUSD',
 'ATUSD.1',
 'AUSDC',
 'AUSDC.1',
 'AUSDT',
 'AUSDT.1',
 'AWBTC',
 'AWBTC.1',
 'AYFI',
 'AYFI.1',
 'AZRX',
 'AZRX.1',
 'Time'}

In [31]:
PATH = f"{PATH_DATA_XLSX}/{xlsxfiles[3]}"

data4 = pd.read_excel(PATH, index_col=0)
data4.head()

,Time,ADAI,AUSDC,ATUSD,ASUSD,AWBTC,AKNC,ABAT,ABUSD,AETH,...,AUSDT.1,AMANA.1,AZRX.1,ASNX.1,AYFI.1,ALINK.1,AREN.1,AREP.1,AENJ.1,ALEND.1
Platform,,,,,,,,,,,,,,,,,,,,,
Aave,2020-10-10T19:48:30.438035456Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3232423846207670,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013900,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:49:53.165059911Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3232423846207670,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013900,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:51:14.445774448Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3232423846207670,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013901,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:52:36.592969518Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3233439206158070,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013901,0.005158,0.000525,0.001148,0.000012,0.000244,9.383126e-07
Aave,2020-10-10T19:53:58.036531289Z,37506682841702496,12434432615852200,2726413009429190,32940425443375300,99307360359226,3233439206158070,973156323988152,22344609370355300,10615036226178800,...,0.020223,0.000173,0.000899,0.013901,0.005158,0.000525,0.001148,0.000012,0.000244,9.383208e-07

In [35]:
PATH = f"{PATH_DATA_CSV}/{csvfiles[0]}"

datacsv = pd.read_csv(PATH, index_col=0)
datacsv.head()

            Price                            Time
Pair
REN/ETH  0.000859    2020-10-10T19:48:44.2540926Z
REN/ETH  0.000859     2020-10-10T19:49:15.780552Z
REN/ETH  0.000859    2020-10-10T19:50:17.5137016Z
REN/ETH  0.000859  2020-10-10T19:51:20.840512299Z
REN/ETH  0.000859    2020-10-10T19:52:29.3277823Z

In [59]:
set(datacsv.index)

{'BAT/ETH',
 'DAI/ETH',
 'ENJ/ETH',
 'KNC/ETH',
 'LEND/ETH',
 'LINK/ETH',
 'MANA/ETH',
 'MKR/ETH',
 'REN/ETH',
 'REP/ETH',
 'SNX/ETH',
 'SUSD/ETH',
 'TUSD/ETH',
 'USDC/ETH',
 'USDT/ETH',
 'WBTC/ETH',
 'YFI/ETH',
 'ZRX/ETH'}

In [36]:
PATH = f"{PATH_DATA_CSV}/{csvfiles[1]}"

datacsv2 = pd.read_csv(PATH, index_col=0)
datacsv2.head()

            Price                            Time
Pair
REN/ETH  0.000859    2020-10-10T19:48:44.2540926Z
REN/ETH  0.000859     2020-10-10T19:49:15.780552Z
REN/ETH  0.000859    2020-10-10T19:50:17.5137016Z
REN/ETH  0.000859  2020-10-10T19:51:20.840512299Z
REN/ETH  0.000859    2020-10-10T19:52:29.3277823Z

In [ ]:
timeseries_pairs = load_data()

for timeseries in timeseries_pairs:
    print(timeseries)
    plot_series(timeseries_pairs[timeseries])
    plt.show()
    break

In [7]:
from os import walk

f = []
for (dirpath, dirnames, filenames) in walk(PATH_DATA):
    print(filenames)
    break

In [15]:
onlyfiles

['Borrow4DEC.xlsx',
 'Lend4DEC.xlsx',
 'Pairs-Price_31OCT.csv',
 'BorrowOCT31.xlsx',
 'PairPrices4DEC.csv',
 'LendOCT31.xlsx']